<?php
/**
 * Created by PhpStorm.
 * User: TinyZ
 * Date: 2016/10/26
 * Time: 22:29
 */

namespace Jxc\Impl\Vo;


use Jxc\Impl\Core\Vo;
use Jxc\Impl\Libs\DateUtil;
use Jxc\Impl\Libs\W2UI;

/**
 * w2ui 产品信息
 */
class VoW2Product extends Vo {

    public $recid;       //  w2grid - recid
    public $pdt_id;      //  货号 -   唯一ID
    public $pdt_counts;  //  库存 array
    public $pdt_zk;      //  折扣
    public $pdt_price;   //  单价

    public function __construct() {
        $this->pdt_zk = 100;
        $this->pdt_counts = array();
        for ($i = 0; $i < 10; $i++) {
            $this->pdt_counts[] = '';
        }
    }

    public function toArray($fields = array()) {
        $map = array();
        if ($fields == null) {
            foreach ($this as $field => $value) {
                $map[$field] = $value;
            }
        } else {
            foreach ($fields as $field) {
                if (isset($this->$field) || property_exists($this, $field)) {
                    $map[$field] = $this->$field;
                }
            }
        }
        return $map;
    }


    public function convert($data) {
        parent::convert($data); // TODO: Change the autogenerated stub
    }



    /**
     * @param $vo VoW2Product
     * @return mixed
     */
    public function voToW2ui($vo) {
        $vo->recid = $vo->pdt_id;
        foreach ($vo->pdt_counts as $k => $v) {
            $f = 'pdt_count_' . $k;
            $vo->$f = $v;
        }
        unset($vo->pdt_counts);
        return $vo;
    }

    public function w2uiToVo($data) {
        $fields = array_keys($data);
        foreach ($fields as $k => $fieldName) {
            if (strpos($fieldName, 'pdt_count_') === 0) {   //  FALSE  不同于 0
                $fields[] = "pdt_counts";
                $var = substr($fieldName, strlen('pdt_count_'));
                if (is_numeric($var))
                    $this->pdt_counts[$var] = $data[$fieldName];
                unset($fields[$k]);
            } else if (isset($this->$fieldName) || property_exists($this, $fieldName)) {
                if (is_array($data[$fieldName]) || is_object($data[$fieldName])) {
                    $this->$fieldName = $data[$fieldName]['text'];
                } else
                    $this->$fieldName = $data[$fieldName];
            } else {
//no-op
            }
        }
    }

    private function calc_total_price() {
        return $this->pdt_total * $this->pdt_price;
    }

    private function calc_pdt_total() {
        $total = 0;
        foreach ($this->pdt_counts as $count) {
            if ($count)
                $total += $count;
        }
        return $total;
    }
}